#!/usr/bin/env python3
"""plot_kpkd_surface.py — Journal-quality 3-D Kp×Kd surface plots for VGOSWEC.

Reads per-flap sweep CSVs from analysis/kpkd_sweep_VGM<angle>.csv and produces:
  analysis/figures/kpkd_surface_VGM<angle>.png  — 3-D surface per flap
  analysis/figures/kpkd_summary.png             — cross-flap summary

Usage:
    python3 scripts/plot_kpkd_surface.py [--outdir analysis/figures]

The CSVs are generated by scripts/sweep_kpkd_vgoswec.sh (real runs) or the
companion generate_sweep_data.py script (synthetic illustrative data).
"""
import argparse
import os
import sys

import matplotlib
matplotlib.use("Agg")  # headless-safe backend
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

try:
    from scipy.interpolate import griddata
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False


# ---------------------------------------------------------------------------
# Per-flap metadata (resonance periods and sweep bands)
# ---------------------------------------------------------------------------
FLAP_META = {
     0: dict(label="VGM-0",  angle=0,  T_res=5.86, omega_n=1.07, band=(3.5, 7.0)),
    10: dict(label="VGM-10", angle=10, T_res=4.29, omega_n=1.46, band=(2.5, 6.0)),
    20: dict(label="VGM-20", angle=20, T_res=4.01, omega_n=1.57, band=(2.5, 6.0)),
    45: dict(label="VGM-45", angle=45, T_res=3.42, omega_n=1.84, band=(2.0, 6.0)),
    90: dict(label="VGM-90", angle=90, T_res=2.99, omega_n=2.10, band=(2.0, 5.0)),
}

# Fixed tuned gains (from per-flap Kp×Kd sweep — see analysis/kpkd_sweep_VGM*.csv)
TUNED_GAINS = {
     0: (4, 1),
    10: (4, 1),
    20: (4, 1),
    45: (4, 2),
    90: (4, 2),
}

# Journal-ready style
JOURNAL_STYLE = {
    "font.family":   "serif",
    "font.size":      10,
    "axes.labelsize": 11,
    "axes.titlesize": 12,
    "figure.dpi":     150,
    "savefig.dpi":    300,
    "savefig.bbox":   "tight",
}


def load_csv(csv_path: str) -> dict:
    """Load sweep CSV into a dict of arrays."""
    import csv
    rows = list(csv.DictReader(open(csv_path)))
    data: dict = {k: [] for k in rows[0].keys()}
    for row in rows:
        for k, v in row.items():
            try:
                data[k].append(float(v))
            except ValueError:
                data[k].append(v)
    return {k: np.array(v) if all(isinstance(x, float) for x in v) else v
            for k, v in data.items()}


def band_integrated_capture(data: dict, flap_angle: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Compute per-(Kp, Kd) band-integrated capture from sweep data.

    Returns (kp_unique, kd_unique, P_grid, feasible_grid).
    P_grid[i,j] = mean over all periods of max(0, P) for Kp=kp_unique[i], Kd=kd_unique[j].
    feasible_grid[i,j] = True if ALL period rows pass all constraints.
    """
    kp_vals = np.unique(data["kp"])
    kd_vals = np.unique(data["kd"])

    P_grid = np.zeros((len(kp_vals), len(kd_vals)))
    feasible_grid = np.ones((len(kp_vals), len(kd_vals)), dtype=bool)

    for i, kp in enumerate(kp_vals):
        for j, kd in enumerate(kd_vals):
            mask = (data["kp"] == kp) & (data["kd"] == kd)
            pw = data["mean_power_w"][mask]
            ps = data["passive_safe"][mask]
            nc = data["no_clamp"][mask]
            po = data["pitch_ok"][mask]
            # Edge rows only for edge_ok check
            edge_ok = data["edge_ok"][mask]

            # Band-integrated capture = mean of per-period P (use max(0,P) for safety)
            P_band = np.maximum(0.0, pw).mean() if len(pw) > 0 else 0.0
            P_grid[i, j] = P_band

            # Feasibility: ALL period points must pass all constraints
            all_pass = (
                np.all(ps == 1) and
                np.all(nc == 1) and
                np.all(po == 1) and
                np.all(edge_ok == 1)
            )
            feasible_grid[i, j] = all_pass

    return kp_vals, kd_vals, P_grid, feasible_grid


def plot_3d_surface(ax3d, kp_vals, kd_vals, P_grid, feasible_grid, meta: dict,
                    tuned: tuple[int, float], vmin: float, vmax: float) -> None:
    """Draw the Kp×Kd 3-D capture surface on ax3d."""
    KD, KP = np.meshgrid(kd_vals, kp_vals)

    # Colour map: viridis for feasible; red/pink for infeasible
    P_plot = P_grid.copy()
    norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
    facecolors = plt.cm.viridis(norm(P_plot))

    # Tint infeasible cells red
    for i in range(len(kp_vals)):
        for j in range(len(kd_vals)):
            if not feasible_grid[i, j]:
                facecolors[i, j] = [0.85, 0.25, 0.25, 0.55]

    surf = ax3d.plot_surface(KD, KP, P_plot, facecolors=facecolors,
                             linewidth=0.3, edgecolor="0.5", antialiased=True)

    # Mark optimal point
    kp_opt, kd_opt = tuned
    kp_idx = np.argmin(np.abs(kp_vals - kp_opt))
    kd_idx = np.argmin(np.abs(kd_vals - kd_opt))
    P_opt = P_grid[kp_idx, kd_idx]
    ax3d.scatter([kd_opt], [kp_opt], [P_opt + 0.005 * (vmax - vmin)],
                 color="gold", s=80, zorder=10, marker="*",
                 label=f"Tuned (Kp={kp_opt}, Kd={kd_opt})")

    ax3d.set_xlabel("$K_d$ [N·m·s/(rad/s)]", labelpad=8)
    ax3d.set_ylabel("$K_p$ [N·m/(rad/s)]", labelpad=8)
    ax3d.set_zlabel("$\\bar{P}_{band}$ [W]", labelpad=8)
    ax3d.set_title(
        f"{meta['label']}  ($\\omega_n$={meta['omega_n']:.2f} rad/s, "
        f"$T_{{res}}$={meta['T_res']:.2f} s)\n"
        f"Band: {meta['band'][0]}–{meta['band'][1]} s  |  "
        f"$\\alpha$=11, $K_i$=5 (fixed)",
        pad=10,
    )
    ax3d.legend(loc="upper left", fontsize=8)

    return surf


def make_colorbar_proxy(fig, vmin, vmax, label="$\\bar{P}_{band}$ [W]"):
    """Add a colorbar to fig for the viridis + infeasible-red color scheme."""
    sm = plt.cm.ScalarMappable(cmap="viridis",
                               norm=mcolors.Normalize(vmin=vmin, vmax=vmax))
    sm.set_array([])
    cb = fig.colorbar(sm, ax=fig.axes, shrink=0.5, pad=0.1, aspect=20)
    cb.set_label(label)
    # Add infeasible legend patch
    from matplotlib.patches import Patch
    cb.ax.annotate("■ infeasible\n  (injects/saturates/\n   pitch > 0.8 rad)",
                   xy=(1.05, 0.02), xycoords="axes fraction",
                   fontsize=7, color="firebrick",
                   bbox=dict(boxstyle="round,pad=0.3", fc="mistyrose", ec="firebrick", alpha=0.7))
    return cb


def main(indir: str, outdir: str) -> None:
    os.makedirs(outdir, exist_ok=True)

    plt.rcParams.update(JOURNAL_STYLE)

    # -----------------------------------------------------------------------
    # Per-flap 3-D surface figures
    # -----------------------------------------------------------------------
    # Global colour scale: consistent across all 5 flaps
    all_P_band: list[float] = []
    all_data: dict = {}
    all_grids: dict = {}

    for angle in FLAP_META:
        csv_path = os.path.join(indir, f"kpkd_sweep_VGM{angle}.csv")
        if not os.path.exists(csv_path):
            print(f"[WARN] Missing sweep CSV: {csv_path}  — skipping VGM-{angle}")
            continue
        data = load_csv(csv_path)
        kp_vals, kd_vals, P_grid, feasible_grid = band_integrated_capture(data, angle)
        all_data[angle] = data
        all_grids[angle] = (kp_vals, kd_vals, P_grid, feasible_grid)
        all_P_band.extend(P_grid[feasible_grid].tolist())

    if not all_grids:
        print("[ERROR] No sweep CSVs found. Run scripts/sweep_kpkd_vgoswec.sh first.")
        sys.exit(1)

    P_global_min = 0.0
    P_global_max = max(all_P_band) * 1.05 if all_P_band else 0.6

    for angle, (kp_vals, kd_vals, P_grid, feasible_grid) in all_grids.items():
        meta = FLAP_META[angle]
        tuned = TUNED_GAINS[angle]

        fig = plt.figure(figsize=(8, 6))
        ax = fig.add_subplot(111, projection="3d")

        surf = plot_3d_surface(ax, kp_vals, kd_vals, P_grid, feasible_grid,
                               meta, tuned, P_global_min, P_global_max)
        make_colorbar_proxy(fig, P_global_min, P_global_max)

        fig.tight_layout(rect=[0, 0, 0.85, 1])

        out_png = os.path.join(outdir, f"kpkd_surface_VGM{angle}.png")
        fig.savefig(out_png)
        plt.close(fig)
        print(f"Saved: {out_png}")

    # -----------------------------------------------------------------------
    # Cross-flap summary figure: optimal band-integrated P vs flap angle
    # -----------------------------------------------------------------------
    angles = sorted(all_grids.keys())
    opt_P_list = []
    opt_kp_list = []
    opt_kd_list = []

    for angle in angles:
        kp_vals, kd_vals, P_grid, feasible_grid = all_grids[angle]
        kp_opt, kd_opt = TUNED_GAINS[angle]
        kp_idx = np.argmin(np.abs(kp_vals - kp_opt))
        kd_idx = np.argmin(np.abs(kd_vals - kd_opt))
        opt_P_list.append(P_grid[kp_idx, kd_idx])
        opt_kp_list.append(kp_opt)
        opt_kd_list.append(kd_opt)

    fig, ax = plt.subplots(figsize=(7, 4))
    colors = plt.cm.viridis(np.linspace(0.2, 0.85, len(angles)))
    bars = ax.bar(np.arange(len(angles)), opt_P_list, color=colors, edgecolor="k", linewidth=0.8)

    for i, (bar, kp, kd, P) in enumerate(zip(bars, opt_kp_list, opt_kd_list, opt_P_list)):
        ax.annotate(
            f"$K_p$={kp}\n$K_d$={kd}",
            xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
            xytext=(0, 6), textcoords="offset points",
            ha="center", va="bottom", fontsize=8,
        )

    T_res_vals = [FLAP_META[a]["T_res"] for a in angles]
    ax.set_xticks(np.arange(len(angles)))
    ax.set_xticklabels(
        [f"VGM-{a}\n($T_{{res}}$={tr:.2f} s)" for a, tr in zip(angles, T_res_vals)],
        fontsize=9,
    )
    ax.set_ylabel("Optimal band-integrated capture $\\bar{P}_{band}$ [W]")
    ax.set_xlabel("Flap angle variant")
    ax.set_title(
        "Cross-flap optimal $K_p$×$K_d$ capture  |  "
        "$\\alpha$=11, $K_i$=5, passive\\_safe=true, clip=10 N·m",
        fontsize=10,
    )
    ax.set_ylim(0, max(opt_P_list) * 1.3)
    ax.grid(axis="y", linestyle="--", alpha=0.5)

    # Annotation: known limitation footnote
    fig.text(
        0.5, 0.01,
        "Note: capture peak sits below resonance due to un-hinge-referred $F_{exc}$ "
        "(see docs/CONTROLLERS.md §Known limitations).",
        ha="center", fontsize=7, style="italic", color="0.5",
    )

    fig.tight_layout(rect=[0, 0.05, 1, 1])
    out_summary = os.path.join(outdir, "kpkd_summary.png")
    fig.savefig(out_summary)
    plt.close(fig)
    print(f"Saved: {out_summary}")

    print("\nAll figures generated successfully.")
    print("Figures written to:", outdir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--indir",  default="analysis",         help="Directory containing sweep CSVs")
    parser.add_argument("--outdir", default="analysis/figures", help="Output directory for figures")
    args = parser.parse_args()
    main(args.indir, args.outdir)
